name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Python with uv
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync --no-install-project

      - name: Run Ruff
        run: uv run ruff check .

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: nadmax/play:${{ github.sha }}
          outputs: type=docker,dest=/tmp/play-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: play-image
          path: /tmp/play-image.tar
          retention-days: 1

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Python with uv
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync --no-install-project

      - name: Run test
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
          POSTGRES_HOST: test:5432
        run: uv run pytest

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    needs: [lint, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Python with uv
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync --no-install-project

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.69.1

      - name: Run Bandit
        run: uv run bandit -r app/

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: play-image
          path: /tmp

      - name: Load Docker image
        run: docker load --input /tmp/play-image.tar

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: nadmax/play:${{ github.sha }}
          severity: "HIGH,CRITICAL"
          format: "sarif"
          output: "trivy-scan-results.sarif"
          skip-setup-trivy: true

      - name: Upload Docker image scan results
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: "trivy-scan-results.sarif"
